version: '3'

services:
  mysql:
    container_name: levelup-db
    image: mysql:8
    platform: linux/amd64
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character_set_server=utf8mb4
      - --collation_server=utf8mb4_general_ci
    networks:
      - levelup-network
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./src/main/resources/db/schema:/docker-entrypoint-initdb.d
    restart: always

  spring:
    container_name: levelup-app
    image: azul/zulu-openjdk-alpine:17
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://levelup-db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&CharacterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_KEY: ${JWT_KEY}
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mysql
    networks:
      - levelup-network
    volumes:
      - ./:/app
    working_dir: /app
    restart: always

networks:
  levelup-network: